export const TUTORIAL_STEPS = [
  {
    id: 'welcome',
    target: '.board-container',
    title: 'Welcome to Catan!',
    description: 'This is your game board. Each hexagonal tile represents a terrain that produces resources when its number is rolled. Let\'s walk through everything you need to know.',
    placement: 'right',
  },
  {
    id: 'terrain',
    target: '.hex-tile',
    title: 'Terrain & Resources',
    description: 'Each terrain type produces a different resource: forests give wood, hills give brick, pastures give sheep, fields give wheat, and mountains give ore. The desert produces nothing.',
    placement: 'right',
  },
  {
    id: 'numbers',
    target: '.number-token',
    title: 'Number Tokens',
    description: 'When the dice total matches a number token, every settlement and city touching that hex collects resources. Numbers like 6 and 8 are rolled most often — look for red numbers!',
    placement: 'right',
  },
  {
    id: 'settlements',
    target: '.board-svg',
    title: 'Settlements & Cities',
    description: 'Build settlements on intersections where hexes meet. Each settlement collects 1 resource from adjacent hexes. Upgrade to a city to collect 2 instead!',
    placement: 'right',
  },
  {
    id: 'roads',
    target: '.board-svg',
    title: 'Roads',
    description: 'Build roads along hex edges to expand your network. You need a connected road to place new settlements. The player with the longest road (5+) earns bonus victory points.',
    placement: 'left',
  },
  {
    id: 'resources',
    target: '.resource-cards',
    title: 'Your Resources',
    description: 'These are your resource cards. You collect them when dice rolls match your hexes. Spend them to build roads, settlements, cities, or buy development cards.',
    placement: 'top',
  },
  {
    id: 'dice',
    target: '.dice-display',
    title: 'Rolling Dice',
    description: 'Click the dice at the start of your turn. All players with settlements on matching hexes collect resources. Watch out — rolling a 7 activates the robber!',
    placement: 'top',
  },
  {
    id: 'build',
    target: '.build-menu',
    title: 'Building',
    description: 'Use these buttons to build roads, settlements, cities, or buy development cards. Right-click any button to see its resource cost. Buttons light up when you can afford them.',
    placement: 'top',
  },
  {
    id: 'trading',
    target: '.trade-panel',
    title: 'Trading',
    description: 'Trade resources with other players or the bank. Player trades let you negotiate — bank trades cost 4:1, but ports can give you better rates like 3:1 or 2:1.',
    placement: 'left',
  },
  {
    id: 'devCards',
    target: '.dev-cards-wrapper',
    title: 'Development Cards',
    description: 'Buy and play special cards for powerful effects. Knights let you move the robber, while others grant free resources or roads. The largest army (3+ knights) earns bonus points.',
    placement: 'top',
  },
  {
    id: 'opponents',
    target: '.opponent-bar',
    title: 'Opponents',
    description: 'Keep an eye on your opponents! Track their resource count, development cards, army size, and victory points. Watch who\'s getting close to winning.',
    placement: 'bottom',
  },
  {
    id: 'turns',
    target: '.turn-indicator',
    title: 'Turn Flow & Winning',
    description: 'Each turn: roll dice, then build and trade freely, then end your turn. First player to reach 10 victory points wins! Settlements are worth 1 point, cities 2.',
    placement: 'top',
  },
];
